name: my_market
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  floating_bottom_navigation_bar: ^1.5.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_storage: ^11.2.5
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  change_app_package_name: ^1.1.0
  font_awesome_flutter: ^10.5.0
  image_picker: ^1.0.5
  provider: ^6.1.1
  uuid: ^4.2.2
  firebase_app_check: ^0.2.1+8
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.18.1
  in_app_purchase: ^3.1.13
  code_builder: ^4.10.0
  cached_network_image: ^3.3.0
  http: ^1.1.0
  html: ^0.15.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  local_auth: ^2.1.8
  flutter_secure_storage: ^9.0.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - images/

  fonts:
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf

